name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Test with .NET
      run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-test-results
        path: TestResults/
      if: ${{ always() }}